### ISSUE TITLE
Can't use multiple instances due to session limitations

### ISSUE THREAD

**Issue by devcamcar** [cloudfoundry-community/etherpad-lite-cf#1]
For curiosity's sake, I was trying to do a multiple instance deployment of Etherpad against Cloud Foundry.  I was able to easily deploy a single instance backed by MySQL as a service (cf-mysql-release).

However, socket.io by default uses an in-memory cache of socket handshakes/connections. That falls apart when you have a round-robin load balancer in front of it. 

Normally we could solve this by using sticky session/connections in HAproxy, but I don't want to fork the HAproxy job in Cloud Foundry's job templates because it feels to heavy handed.

What I'd like to be able to do is use socket.io's support for backending to Redis now that cf-redis-release (https://github.com/pivotal-cf/cf-redis-release) is open sourced.

**Comment by ArthurHlt** [comment]
In fact this problem is due to etherpad-lite, it can't support multi-instance cause it can't handle when two etherpad-lite write in the same database. By default, I mean without cloudfoundry you can't use etherpad-lite with multiple instances.

For sticky session you should rename the token name by JSESSIONID in the this is how works sticky session on cloudfoundry (and it's handle by the gorouter look at [here](https://github.com/cloudfoundry/gorouter/issues/26) ), anyway it will not work for etherpad-lite unfortunately.

For redis, i'm not sure about what you're asking but if you bind your redis service from your service broker and said to etherpad-lite what is your service name it should work. In fact, this fork will try to find the `uri` value from your service credentials and if my memory is good this service broker give in its credentials this value.
