### ISSUE TITLE
errors with node 0.12.x

### ISSUE THREAD

**Issue by Feldhacker** [cloudfoundry-community/etherpad-lite-cf#2]
I tried deploying v1.5.6, which generated lots of compile errors, presumably because node v0.12.4 was attempting to be used.
I modified the package.json to specify:
 "engines": {
    "node": "0.10.37",
    "npm": "2.13.0"
  },
...and then it deployed fine.

**Comment by ArthurHlt** [comment]
This is normally fine, can you give the version of your buildpack? 
There is no error about this in my cloud foundry

**Comment by Feldhacker** [comment]
nodejs_buildpack-cached-v1.4.0.zip

**Comment by flavorjones** [comment]
I've confirmed the behavior Feldhacker described. Node 0.12 will fail to compile during `node-gyp rebuild`. The changes he suggested above fix the issue by pinning the node version to 0.10.x.

node 0.12 has been supported in the nodejs-buildpack since v1.2.1.

I'm submitting a PR right now ... see #3.

**Comment by ArthurHlt** [comment]
Thanks for the PR, I was thinking maybe move to 0.12

**Comment by ArthurHlt** [comment]
Keep it open to remember to move on 0.12

**Comment by ArthurHlt** [comment]
done
